import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../dist/sw.js',import.meta.url),'utf8');
function worker(base='/'){const events={},calls=[],messages=[];const clients=new Map([['tab-a',{id:'tab-a',url:'https://iamtt.test'+base,postMessage:m=>messages.push(m)}],['tab-b',{id:'tab-b',url:'https://iamtt.test'+base,postMessage:m=>messages.push(m)}]]);const context={URL,Headers,Response,Request,Map,Promise,Number,Date,decodeURIComponent,setTimeout:(f,ms)=>{const t=setTimeout(f,ms);t.unref();return t},self:{location:{origin:'https://iamtt.test',href:'https://iamtt.test'+base+'sw.js'},addEventListener:(name,fn)=>events[name]=fn,clients:{get:async id=>clients.get(id)}},fetch:async(url,options)=>{calls.push({url,options});return new Response('0123456789',{status:206,headers:{'Content-Type':'video/mp4','Content-Length':'10','Content-Range':'bytes 100-109/1000'}})}};vm.runInNewContext(source,context);return {events,calls,messages,clients,base}}
function authorize(w,id,token='secret-access-token'){w.events.message({source:w.clients.get(id),data:{type:'AUTH',token,expiresAt:Date.now()+3600000,files:[{id:'file_12345',size:1000,mimeType:'video/mp4'}]},ports:[]})}
async function request(w,clientId,path='/drive-media/file_12345'){let result;w.events.fetch({clientId,request:new Request('https://iamtt.test'+w.base+path.replace(/^\//,''),{headers:{Range:'bytes=100-109'}}),respondWith:p=>result=p});return result}
test('byte ranges and streaming body are forwarded; token appears only in the authorization header',async()=>{const w=worker();authorize(w,'tab-a');const r=await request(w,'tab-a');assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),'bytes 100-109/1000');assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(await r.text(),'0123456789');assert.equal(w.calls[0].options.headers.get('Range'),'bytes=100-109');assert.equal(w.calls[0].options.headers.get('Authorization'),'Bearer secret-access-token');assert.ok(!w.calls[0].url.includes('secret-access-token'));assert.equal(w.calls[0].options.credentials,'omit')});
test('a selected-file allowlist rejects other Drive IDs without contacting Google',async()=>{const w=worker();authorize(w,'tab-a');const r=await request(w,'tab-a','/drive-media/other_file');assert.equal(r.status,403);assert.equal(w.calls.length,0)});
test('another tab cannot reuse the first tab credentials',async()=>{const w=worker();authorize(w,'tab-a','token-a');authorize(w,'tab-b','');const r=await request(w,'tab-b');assert.equal(r.status,401);assert.equal(w.calls.length,0)});
test('disconnect clears a tab session',async()=>{const w=worker();authorize(w,'tab-a');w.events.message({source:w.clients.get('tab-a'),data:{type:'CLEAR_AUTH'},ports:[]});const r=await request(w,'tab-a');assert.equal(r.status,401);assert.equal(w.calls.length,0)});
test('cross-origin messages cannot inject credentials',async()=>{const w=worker();w.events.message({source:{id:'tab-a',url:'https://other.test/'},data:{type:'AUTH',token:'attacker',expiresAt:Date.now()+3600000,files:[{id:'file_12345'}]},ports:[]});authorize(w,'tab-a','');const r=await request(w,'tab-a');assert.equal(r.status,401);assert.equal(w.calls.length,0)});

test('GitHub Pages project path intercepts private media and forwards its byte range',async()=>{const w=worker('/IAMTT-streaming-apps/');authorize(w,'tab-a');const r=await request(w,'tab-a');assert.equal(r.status,206);assert.match(w.calls[0].url,/\/files\/file_12345\?/);assert.equal(w.calls[0].options.headers.get('Range'),'bytes=100-109')});
test('project service worker ignores media paths outside its project',()=>{const w=worker('/IAMTT-streaming-apps/');let handled=false;w.events.fetch({clientId:'tab-a',request:new Request('https://iamtt.test/drive-media/file_12345'),respondWith:()=>handled=true});assert.equal(handled,false)});
