package com.iamtt.downloader;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.core.app.ActivityScenario;
import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.libtorrent4j.*;
import org.libtorrent4j.swig.torrent_flags_t;
import java.io.*;
import java.nio.file.Files;
import java.util.*;

@RunWith(AndroidJUnit4.class)
public class NativeEngineTest {
    @Test public void crashReportIsReadableAndRemovesLinks() {
        android.content.Context c=InstrumentationRegistry.getInstrumentation().getTargetContext();
        assertTrue(CrashReports.report(c).contains("IAMTT v"));
        String privateLink="https://example.org/private-token/manifest.json";
        assertFalse(CrashReports.redact("failed "+privateLink).contains("private-token"));
    }
    @Test public void standaloneAppLaunches() {
        try(ActivityScenario<MainActivity> activity=ActivityScenario.launch(MainActivity.class)) {
            activity.onActivity(a->assertEquals("com.iamtt.downloader",a.getPackageName()));
        }
    }
    @Test public void nativeEngineTransfersOriginalFixtureOverLoopback() throws Exception {
        // Generated bytes, no external torrents or movie downloads in tests.
        File root=new File(InstrumentationRegistry.getInstrumentation().getTargetContext().getCacheDir(),"native-test-"+System.nanoTime());
        File seed=new File(root,"seed"),target=new File(root,"target");assertTrue(seed.mkdirs());assertTrue(target.mkdirs());
        byte[] original=new byte[262144];new Random(42).nextBytes(original);
        File movie=new File(seed,"fixture.mp4");Files.write(movie.toPath(),original);
        TorrentInfo info=new TorrentInfo(new TorrentBuilder().path(movie).flags(TorrentBuilder.V1_ONLY).generate().entry().bencode());
        SessionManager source=new SessionManager(),destination=new SessionManager();
        try {
            SettingsPack a=new SettingsPack();a.listenInterfaces("127.0.0.1:16881");a.setEnableDht(false);a.setEnableLsd(false);
            SettingsPack b=new SettingsPack();b.listenInterfaces("127.0.0.1:16882");b.setEnableDht(false);b.setEnableLsd(false);
            source.start(new SessionParams(a));destination.start(new SessionParams(b));
            source.download(info,seed);
            TorrentHandle sh=awaitHandle(source,info);
            long until=System.currentTimeMillis()+20000;
            while(!sh.status(true).isSeeding()&&System.currentTimeMillis()<until)Thread.sleep(200);
            assertTrue("Fixture should become a seed",sh.status(true).isSeeding());
            destination.download(info,target,null,new Priority[]{Priority.DEFAULT},Collections.singletonList(new TcpEndpoint("127.0.0.1",16881)),new torrent_flags_t());
            TorrentHandle dh=awaitHandle(destination,info);
            until=System.currentTimeMillis()+60000;
            while(!dh.status(true).isFinished()&&System.currentTimeMillis()<until)Thread.sleep(250);
            assertTrue("Local torrent transfer should complete",dh.status(true).isFinished());
            assertArrayEquals(original,Files.readAllBytes(new File(target,"fixture.mp4").toPath()));
        } finally {destination.stop();source.stop();delete(root);}
    }
    private TorrentHandle awaitHandle(SessionManager session,TorrentInfo info) throws Exception {
        long until=System.currentTimeMillis()+10000;TorrentHandle handle;
        do{handle=session.find(info.infoHash());if(handle!=null&&handle.isValid())return handle;Thread.sleep(100);}while(System.currentTimeMillis()<until);
        throw new AssertionError("Torrent handle was not created");
    }
    private void delete(File file){File[] children=file.listFiles();if(children!=null)for(File child:children)delete(child);file.delete();}
}
