package com.iamtt.downloader;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.core.app.ActivityScenario;
import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.libtorrent4j.*;
import org.libtorrent4j.swig.torrent_flags_t;
import java.io.*;
import java.nio.file.Files;
import java.util.*;

@RunWith(AndroidJUnit4.class)
public class NativeEngineTest {
    @Test public void crashReportIsReadableAndRemovesLinks() {
        android.content.Context c=InstrumentationRegistry.getInstrumentation().getTargetContext();
        assertTrue(CrashReports.report(c).contains("IAMTT v"));
        String privateLink="https://example.org/private-token/manifest.json";
        assertFalse(CrashReports.redact("failed "+privateLink).contains("private-token"));
    }
    @Test public void standaloneAppLaunches() {
        try(ActivityScenario<MainActivity> activity=ActivityScenario.launch(MainActivity.class)) {
            activity.onActivity(a->assertEquals("com.iamtt.downloader",a.getPackageName()));
        }
    }
    @Test public void nativeEngineTransfersOriginalFixtureOverLoopback() throws Exception {
        // Generated bytes, no external torrents or movie downloads in tests.
        File root=new File(InstrumentationRegistry.getInstrumentation().getTargetContext().getCacheDir(),"native-test-"+System.nanoTime());
        File seed=new File(root,"seed"),target=new File(root,"target");assertTrue(seed.mkdirs());assertTrue(target.mkdirs());
        byte[] original=new byte[262144];new Random(42).nextBytes(original);
        File movie=new File(seed,"fixture.mp4");Files.write(movie.toPath(),original);
        TorrentInfo info=new TorrentInfo(new TorrentBuilder().path(movie).flags(TorrentBuilder.V1_ONLY).generate().entry().bencode());
        SessionManager source=new SessionManager(),destination=new SessionManager();
        try {
            SettingsPack a=new SettingsPack();a.listenInterfaces("127.0.0.1:16881");a.setEnableDht(false);a.setEnableLsd(false);
            SettingsPack b=new SettingsPack();b.listenInterfaces("127.0.0.1:16882");b.setEnableDht(false);b.setEnableLsd(false);
            source.start(new SessionParams(a));destination.start(new SessionParams(b));
            source.download(info,seed);
            TorrentHandle sh=awaitHandle(source,info);
            long until=System.currentTimeMillis()+20000;
            while(!sh.status(true).isSeeding()&&System.currentTimeMillis()<until)Thread.sleep(200);
            assertTrue("Fixture should become a seed",sh.status(true).isSeeding());
            destination.download(info,target,null,new Priority[]{Priority.DEFAULT},Collections.singletonList(new TcpEndpoint("127.0.0.1",16881)),new torrent_flags_t());
            TorrentHandle dh=awaitHandle(destination,info);
            until=System.currentTimeMillis()+60000;
            while(!dh.status(true).isFinished()&&System.currentTimeMillis()<until)Thread.sleep(250);
            assertTrue("Local torrent transfer should complete",dh.status(true).isFinished());
            assertArrayEquals(original,Files.readAllBytes(new File(target,"fixture.mp4").toPath()));
        } finally {destination.stop();source.stop();delete(root);}
    }
    @Test public void foregroundServiceKeepsTransferringWhileScreenIsOpen() throws Exception {
        android.content.Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
        try(android.os.ParcelFileDescriptor permission=InstrumentationRegistry.getInstrumentation().getUiAutomation().executeShellCommand("appops set com.iamtt.downloader MANAGE_EXTERNAL_STORAGE allow")){
            try(InputStream response=new android.os.ParcelFileDescriptor.AutoCloseInputStream(permission)){while(response.read()!=-1){}}
        }
        assertTrue("Shared file permission granted",DownloadFiles.allowed(context));
        DownloadStore store=DownloadStore.get(context);store.pauseAll();store.wifiOnly(false);
        store.folder(DownloadFiles.defaultFolder()+"/service-test-"+System.nanoTime());
        File root=new File(context.getCacheDir(),"service-test-"+System.nanoTime());assertTrue(root.mkdirs());
        byte[] original=new byte[8*1024*1024];new Random(System.nanoTime()).nextBytes(original);
        File video=new File(root,"service-fixture.mp4");Files.write(video.toPath(),original);
        java.net.ServerSocket tracker=new java.net.ServerSocket(0,10,java.net.InetAddress.getByName("127.0.0.1"));
        SessionManager seed=new SessionManager();SettingsPack settings=new SettingsPack();
        settings.listenInterfaces("127.0.0.1:17881");settings.setEnableDht(false);settings.setEnableLsd(false);settings.uploadRateLimit(65536);
        Entry entry=new TorrentBuilder().path(video).flags(TorrentBuilder.V1_ONLY).generate().entry();
        String trackerUrl="http://127.0.0.1:"+tracker.getLocalPort()+"/announce";
        entry.dictionary().put("announce",new Entry(trackerUrl));TorrentInfo info=new TorrentInfo(entry.bencode());
        Thread server=new Thread(()->{
            while(!tracker.isClosed())try(java.net.Socket socket=tracker.accept()){
                socket.setSoTimeout(5000);BufferedReader reader=new BufferedReader(new InputStreamReader(socket.getInputStream(),java.nio.charset.StandardCharsets.US_ASCII));
                String line;while((line=reader.readLine())!=null&&!line.isEmpty()){}
                byte[] response=Entry.fromMap(new HashMap<String,Object>(){{put("interval",5);put("complete",1);put("incomplete",0);put("peers",Collections.singletonList(new HashMap<String,Object>(){{put("ip","127.0.0.1");put("port",17881);}}));}}).bencode();
                OutputStream out=socket.getOutputStream();out.write(("HTTP/1.1 200 OK\r\nContent-Length: "+response.length+"\r\nConnection: close\r\n\r\n").getBytes(java.nio.charset.StandardCharsets.US_ASCII));out.write(response);out.flush();
            }catch(Exception ignored){}
        },"fixture-tracker");server.setDaemon(true);server.start();
        DownloadStore.Item job=null;
        try(ActivityScenario<MainActivity> activity=ActivityScenario.launch(new android.content.Intent(context,MainActivity.class).putExtra("downloads",true))){
            seed.start(new SessionParams(settings));seed.download(info,root);TorrentHandle sh=awaitHandle(seed,info);sh.setUploadLimit(65536);
            long until=System.currentTimeMillis()+20000;while(!sh.status(true).isSeeding()&&System.currentTimeMillis()<until)Thread.sleep(100);
            assertTrue("Fixture seed ready",sh.status(true).isSeeding());
            org.json.JSONObject stream=new org.json.JSONObject().put("infoHash",info.infoHash().toHex()).put("fileIdx",0).put("sources",new org.json.JSONArray().put("tracker:"+trackerUrl));
            job=store.add(stream,"Original service test fixture");
            activity.onActivity(a->DownloadService.start(a));
            until=System.currentTimeMillis()+90000;
            while(job.done==0&&!job.state.equals("Error")&&System.currentTimeMillis()<until)Thread.sleep(250);
            assertTrue("Foreground service must receive real bytes: "+job.state+" "+job.detail,job.done>0);
            long before=job.done;
            // Continue through repeated stats polling, saves and notifications,
            // well beyond the few seconds reported on the user's phone.
            for(int tick=0;tick<45;tick++){
                Thread.sleep(1000);assertFalse("Service stopped unexpectedly: "+job.detail,job.state.equals("Error"));
                activity.onActivity(a->assertFalse(a.isFinishing()));
            }
            assertTrue("Data must continue increasing",job.done>before);
            assertEquals("Downloading",job.state);
            assertTrue("Bytes are written directly to the configured public folder",job.path.startsWith(store.folder()+"/"));
            assertTrue("Public download file exists",new File(job.path).isFile());
            File ownedRoot=new File(job.folder);File neighbour=new File(store.folder(),"keep.txt");Files.write(neighbour.toPath(),new byte[]{1,2,3});
            store.delete(job);activity.onActivity(a->DownloadService.start(a));
            until=System.currentTimeMillis()+20000;while(store.find(job.id)!=null&&System.currentTimeMillis()<until)Thread.sleep(100);
            assertNull("Deletion stops the active transfer and removes the entry",store.find(job.id));
            assertFalse("Partial files are deleted",ownedRoot.exists());
            assertTrue("Other files in the selected folder are kept",neighbour.isFile());neighbour.delete();
            File oldPrivate=new File(new File(context.getFilesDir(),"downloads"),info.infoHash().toHex()+"/legacy.mp4");assertTrue(oldPrivate.getParentFile().mkdirs());
            byte[] legacyBytes={4,5,6,7};Files.write(oldPrivate.toPath(),legacyBytes);
            DownloadStore.Item legacy=store.add(stream,"Earlier completed video");legacy.path=oldPrivate.getAbsolutePath();legacy.total=legacyBytes.length;legacy.done=legacyBytes.length;legacy.state="Complete";store.save();
            store.move(legacy);activity.onActivity(a->DownloadService.start(a));
            until=System.currentTimeMillis()+20000;while(legacy.moveRequested&&System.currentTimeMillis()<until)Thread.sleep(100);
            assertEquals("Complete",legacy.state);assertFalse("Private original removed after successful move",oldPrivate.exists());
            assertTrue("Moved video is in selected shared folder",legacy.path.startsWith(store.folder()+"/"));
            assertArrayEquals(legacyBytes,Files.readAllBytes(new File(legacy.path).toPath()));
            store.delete(legacy);activity.onActivity(a->DownloadService.start(a));
            until=System.currentTimeMillis()+20000;while(store.find(legacy.id)!=null&&System.currentTimeMillis()<until)Thread.sleep(100);
            assertNull("Completed entry deleted",store.find(legacy.id));assertFalse("Completed video deleted",new File(legacy.path).exists());new File(store.folder()).delete();
        }finally{
            if(job!=null){job.state="Paused";store.save();}
            Thread.sleep(1500);context.stopService(new android.content.Intent(context,DownloadService.class));
            tracker.close();server.join(2000);seed.stop();delete(root);
        }
    }

    private TorrentHandle awaitHandle(SessionManager session,TorrentInfo info) throws Exception {
        long until=System.currentTimeMillis()+10000;TorrentHandle handle;
        do{handle=session.find(info.infoHash());if(handle!=null&&handle.isValid())return handle;Thread.sleep(100);}while(System.currentTimeMillis()<until);
        throw new AssertionError("Torrent handle was not created");
    }
    private void delete(File file){File[] children=file.listFiles();if(children!=null)for(File child:children)delete(child);file.delete();}
}
