plugins { id 'com.android.application' }
android {
    namespace 'com.iamtt.downloader'
    compileSdk 35
    defaultConfig {
        applicationId 'com.iamtt.downloader'
        minSdk 28
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        versionCode Integer.parseInt(System.getenv('GITHUB_RUN_NUMBER') ?: '1')
        versionName '0.1.' + (System.getenv('GITHUB_RUN_NUMBER') ?: '0')
    }
    signingConfigs {
        prototype {
            storeFile file('prototype.keystore')
            storePassword 'android'
            keyAlias 'prototype'
            keyPassword 'android'
        }
    }
    buildTypes { debug { signingConfig signingConfigs.prototype } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildFeatures { buildConfig true }
    packaging { jniLibs { useLegacyPackaging = true } }
}
dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.libtorrent4j:libtorrent4j:2.1.0-39'
    implementation 'org.libtorrent4j:libtorrent4j-android-arm64:2.1.0-39'
    implementation 'org.libtorrent4j:libtorrent4j-android-arm:2.1.0-39'
    implementation 'org.libtorrent4j:libtorrent4j-android-x86_64:2.1.0-39'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:core:1.6.1'
}
